# Generated by Django 4.0.2 on 2022-02-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.TextField(default='default title', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
