# Generated by Django 4.0.2 on 2022-03-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0002_alter_reviews_options_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.TextField(verbose_name='Имя1'),
        ),
    ]
