# Generated by Django 4.0.2 on 2022-03-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0003_alter_reviews_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsZoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField(verbose_name='Имя')),
                ('review1', models.TextField(verbose_name='Отзыв')),
                ('date1', models.TextField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
    ]
