# Generated by Django 4.0.2 on 2022-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0005_reviewsyoll_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsyoll',
            name='rating2',
            field=models.TextField(default='', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
