# Generated by Django 4.0.2 on 2022-03-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0006_reviewsyoll_rating2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы Yandex', 'verbose_name_plural': 'Отзывы Yandex'},
        ),
        migrations.AlterModelOptions(
            name='reviewsyoll',
            options={'verbose_name': 'Отзывы Yoll', 'verbose_name_plural': 'Отзывы Yoll'},
        ),
        migrations.AlterModelOptions(
            name='reviewszoon',
            options={'verbose_name': 'Отзывы Zoon', 'verbose_name_plural': 'Отзывы Zoon'},
        ),
    ]
