# Generated by Django 4.0.2 on 2022-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nero1', '0007_alter_reviews_options_alter_reviewsyoll_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewszoon',
            name='rating1',
            field=models.TextField(default='', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
